version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 98944211
      POSTGRES_DB: FastAPI
    volumes:
      - ./vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
networks:
    mynetwork: